export enum HttpCode {
    CONTINUE = 100,
    SWITCHING_PROTOCOLS = 101,
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTHORITATIVE_INFORMATION = 203,
    NO_CONTENT = 204,
    RESET_CONTENT = 205,
    PARTIAL_CONTENT = 206,
    MULTI_STATUS = 207,
    ALREADY_REPORTED = 208,
    IM_USED = 226,
    MULTIPLE_CHOICES = 300,
    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    SEE_OTHER = 303,
    NOT_MODIFIED = 304,
    USE_PROXY = 305,
    SWITCH_PROXY = 306,
    TEMPORARY_REDIRECT = 307,
    PERMANENT_REDIRECT = 308,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTHENTICATION_REQUIRED = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    REQUEST_ENTITY_TOO_LARGE = 413,
    REQUEST_URI_TOO_LONG = 414,
    UNSUPPORTED_MEDIA_TYPE = 415,
    REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    EXPECTATION_FAILED = 417,
    IM_A_TEAPOT = 418,
    MISDIRECTED_REQUEST = 421,
    UNPROCESSABLE_ENTITY = 422,
    UPGRADE_REQUIRED = 426,
    PRECONDITION_REQUIRED = 428,
    LOCKED = 423,
    FAILED_DEPENDENCY = 424,
    TOO_MANY_REQUESTS = 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    UNAVAILABLE_FOR_LEGAL_REASONS = 451,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_VERSION_NOT_SUPPORTED = 505,
    VARIANT_ALSO_NEGOTIATES = 506,
    INSUFFICIENT_STORAGE = 507,
    LOOP_DETECTED = 508,
    NOT_EXTENDED = 510,
    NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export const HttpCodeMap: Record<number, string> = {
    [HttpCode.CONTINUE]: 'Continue',
    [HttpCode.SWITCHING_PROTOCOLS]: 'Switching Protocols',
    [HttpCode.OK]: 'OK',
    [HttpCode.CREATED]: 'Created',
    [HttpCode.ACCEPTED]: 'Accepted',
    [HttpCode.NON_AUTHORITATIVE_INFORMATION]: 'Non-Authoritative Information',
    [HttpCode.NO_CONTENT]: 'No Content',
    [HttpCode.RESET_CONTENT]: 'Reset Content',
    [HttpCode.PARTIAL_CONTENT]: 'Partial Content',
    [HttpCode.MULTI_STATUS]: 'Multi Status',
    [HttpCode.ALREADY_REPORTED]: 'Already Reported',
    [HttpCode.IM_USED]: 'IM Used',
    [HttpCode.MULTIPLE_CHOICES]: 'Multiple Choices',
    [HttpCode.MOVED_PERMANENTLY]: 'Moved Permanently',
    [HttpCode.FOUND]: 'Found',
    [HttpCode.SEE_OTHER]: 'See Other',
    [HttpCode.NOT_MODIFIED]: 'Not Modified',
    [HttpCode.USE_PROXY]: 'Use Proxy',
    [HttpCode.SWITCH_PROXY]: 'Switch Proxy',
    [HttpCode.TEMPORARY_REDIRECT]: 'Temporary Redirect',
    [HttpCode.PERMANENT_REDIRECT]: 'Permanent Redirect',
    [HttpCode.BAD_REQUEST]: 'Bad Request',
    [HttpCode.UNAUTHORIZED]: 'Unauthorized',
    [HttpCode.PAYMENT_REQUIRED]: 'Payment Required',
    [HttpCode.FORBIDDEN]: 'Forbidden',
    [HttpCode.NOT_FOUND]: 'Not Found',
    [HttpCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
    [HttpCode.NOT_ACCEPTABLE]: 'Not Acceptable',
    [HttpCode.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
    [HttpCode.REQUEST_TIMEOUT]: 'Request Time-out',
    [HttpCode.CONFLICT]: 'Conflict',
    [HttpCode.GONE]: 'Gone',
    [HttpCode.LENGTH_REQUIRED]: 'Length Required',
    [HttpCode.PRECONDITION_FAILED]: 'Precondition Failed',
    [HttpCode.REQUEST_ENTITY_TOO_LARGE]: 'Request Entity Too Large',
    [HttpCode.REQUEST_URI_TOO_LONG]: 'Request-URI Too Large',
    [HttpCode.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
    [HttpCode.REQUESTED_RANGE_NOT_SATISFIABLE]: 'Requested Range not Satisfiable',
    [HttpCode.EXPECTATION_FAILED]: 'Expectation Failed',
    [HttpCode.IM_A_TEAPOT]: 'I\'m a teapot',
    [HttpCode.MISDIRECTED_REQUEST]: 'Misdirected Request',
    [HttpCode.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
    [HttpCode.UPGRADE_REQUIRED]: 'Locked',
    [HttpCode.PRECONDITION_REQUIRED]: 'Failed Dependency',
    [HttpCode.LOCKED]: 'Upgrade Required',
    [HttpCode.FAILED_DEPENDENCY]: 'Precondition Required',
    [HttpCode.TOO_MANY_REQUESTS]: 'Too Many Requests',
    [HttpCode.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
    [HttpCode.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',
    [HttpCode.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
    [HttpCode.NOT_IMPLEMENTED]: 'Not Implemented',
    [HttpCode.BAD_GATEWAY]: 'Bad Gateway',
    [HttpCode.SERVICE_UNAVAILABLE]: 'Service Unavailable',
    [HttpCode.GATEWAY_TIMEOUT]: 'Gateway Time-out',
    [HttpCode.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version not Supported',
    [HttpCode.VARIANT_ALSO_NEGOTIATES]: 'Variant Also Negotiates',
    [HttpCode.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
    [HttpCode.LOOP_DETECTED]: 'Loop Detected',
    [HttpCode.NOT_EXTENDED]: 'Not Extended',
    [HttpCode.NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
};
